# Generated by Django 2.2 on 2019-05-07 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190507_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about_messages', to=settings.AUTH_USER_MODEL, verbose_name='О ком'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
