# Generated by Django 2.2 on 2019-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190507_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
    ]
