# Generated by Django 2.2 on 2019-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_message_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет звезды',
                'verbose_name_plural': 'Цвета звезд',
            },
        ),
    ]
