# Generated by Django 2.2 on 2019-05-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_starcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star_color',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profiles.StarColor', verbose_name='Цвет звезды'),
        ),
    ]
