# Generated by Django 2.2 on 2019-05-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_user_star_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='star_color',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='profiles.StarColor', verbose_name='Цвет звезды'),
        ),
    ]
