# Generated by Django 2.2 on 2019-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_starcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starcolor',
            name='color',
            field=models.CharField(default='#ffffff', max_length=250, verbose_name='Код цвета'),
        ),
    ]
