# Generated by Django 2.2 on 2019-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20190514_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.PositiveIntegerField(default=0, verbose_name='Претензии'),
        ),
        migrations.AddField(
            model_name='user',
            name='complaints',
            field=models.PositiveIntegerField(default=0, verbose_name='Жалобы'),
        ),
        migrations.AddField(
            model_name='user',
            name='thanks',
            field=models.PositiveIntegerField(default=0, verbose_name='Благодарности'),
        ),
    ]
