# Generated by Django 2.2 on 2019-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190515_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claims',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Претензии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='complaints',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thanks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Благодарности'),
        ),
    ]
