# Generated by Django 2.2 on 2019-04-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['name'], 'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
    ]
