# Generated by Django 2.2 on 2019-04-18 08:11

import announcements.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_auto_20190418_1105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='Размещено')),
                ('views', models.PositiveSmallIntegerField(verbose_name='Просмотры')),
                ('address', models.CharField(max_length=250, verbose_name='Адресс')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='services.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
                'ordering': ['posted'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=announcements.models.Image.get_picture_url, verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='announcements.Announcement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
