# Generated by Django 2.2 on 2019-04-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['posted'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='views',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Просмотры'),
        ),
    ]
