# Generated by Django 2.2 on 2019-04-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20190418_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
