# Generated by Django 2.2 on 2019-04-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='announcements.City', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
