# Generated by Django 2.2 on 2019-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20190418_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='contact',
            field=models.CharField(default='Иванов Иван', max_length=250, verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone',
            field=models.CharField(default='88005553535', max_length=250, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
