# Generated by Django 2.2 on 2019-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='today',
            field=models.DateField(blank=True, null=True, verbose_name='Сегодня'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views_today',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Просмотры сегодня'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Город'),
        ),
    ]
