# Generated by Django 2.2 on 2019-04-19 06:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20190419_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
