# Generated by Django 2.2 on 2019-04-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20190429_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='can_edit',
            field=models.DateTimeField(null=True, verbose_name='Возможно редактирование до'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='today',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Сегодня'),
        ),
    ]
