# Generated by Django 2.2 on 2019-05-06 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20190429_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 10, 6, 0, 616515), verbose_name='Размещено'),
        ),
    ]
