# Generated by Django 2.2 on 2019-05-06 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20190506_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 10, 8, 12, 364819), verbose_name='Размещено'),
        ),
    ]
