# Generated by Django 2.2 on 2019-05-06 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20190506_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 10, 10, 48, 504938), verbose_name='Размещено'),
        ),
    ]
