# Generated by Django 2.2 on 2019-05-06 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_auto_20190506_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 10, 15, 36, 78511), verbose_name='Размещено'),
        ),
    ]
