# Generated by Django 2.2 on 2019-05-06 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_auto_20190506_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 7, 16, 31, 14663, tzinfo=utc), verbose_name='Размещено'),
        ),
    ]
