# Generated by Django 2.2 on 2019-05-06 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_auto_20190506_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Размещено'),
        ),
    ]
