# Generated by Django 2.2 on 2019-05-06 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_auto_20190506_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
    ]
