# Generated by Django 2.2 on 2019-05-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_announcement_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='updated',
        ),
    ]
